routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/admin')->middleware('can:update-books')->group(function() {
    Route::get('/', 'AdminsController@index')->name('admin.index');

    Route::resource('/books', 'BooksController');
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/authors', 'AuthorsController');
    Route::resource('/publishers', 'PublishersController');
    Route::resource('/users', 'UsersController')->middleware('can:update-users');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'GalleryController@index')->name('gallery.index');
Route::get('/search', 'GalleryController@search')->name('search');

Route::get('/book/{book}', 'BooksController@details')->name('book.details');
Route::post('/book/{book}/rate', 'BooksController@rate')->name('book.rate');

Route::post('/cart', 'CartController@addToCart')->name('cart.add')->middleware('auth');
Route::get('/cart', 'CartController@viewCart')->name('cart.view');
Route::post('/removeOne/{book}', 'CartController@removeOne')->name('cart.remove_one');
Route::post('/removeAll/{book}', 'CartController@removeAll')->name('cart.remove_all');


Route::get('/execute', 'PurchaseController@executePayment');
Route::post('/create-payment', 'PurchaseController@createPayment')->name('payment.create');

resources/views/theme/default.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>لوحة الإدارة - مكتبة حسوب</title>

  <!-- Custom fonts for this template-->
  <link href="{!! asset('theme/vendor/fontawesome-free/css/all.min.css') !!}" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{!! asset('theme/css/sb-admin-2.min.css') !!}" rel="stylesheet">
    <style>
        .sidebar.toggled .nav-item .nav-link {
            text-align: center !important;
        }
        .sidebar #sidebarToggle::after {
            content: '\f105';
        }
        .sidebar.toggled #sidebarToggle::after {
            content: '\f104';

        }
    </style>
    @yield('head')
</head>

<body id="page-top" dir="rtl" style="text-align: right">

  <!-- Page Wrapper -->
  <div id="wrapper">

    @include('theme.sidebar')
    
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        @include('theme.header')

        <!-- Begin Page Content -->
        <div class="container-fluid">

        @if(Session::has('flash_message'))
            <div class="p-3 mb-2 bg-success text-white rounded text-center">
                {{session('flash_message')}}
            </div>  
        @endif

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">@yield('title')</h1>
          </div>

          <!-- Content Row -->
          @yield('content')

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      @include('theme.footer')

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{!! asset('theme/vendor/jquery/jquery.min.js') !!}"></script>
  <script src="{!! asset('theme/vendor/bootstrap/js/bootstrap.bundle.min.js') !!}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{!! asset('theme/vendor/jquery-easing/jquery.easing.min.js') !!}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{!! asset('theme/js/sb-admin-2.min.js') !!}"></script>

  <!-- Page level plugins -->
  <script src="{!! asset('theme/vendor/chart.js/Chart.min.js') !!}"></script>

  <!-- Page level custom scripts -->
  <script src="{!! asset('theme/js/demo/chart-area-demo.js') !!}"></script>
  <script src="{!! asset('theme/js/demo/chart-pie-demo.js') !!}"></script>

@yield('script')

</body>

</html>

resources/views/theme/footer.blade.php
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
        <span>جميع الحقوق محفوظة &copy; 2019</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

resources/views/theme/header.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
<div class="mr-4 lead"><b>@yield('heading')</b></div>

<!-- Sidebar Toggle (Topbar) -->
<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
  <i class="fa fa-bars"></i>
</button>

<!-- Topbar Navbar -->
<ul class="navbar-nav mr-auto">
  
  <div class="topbar-divider d-none d-sm-block"></div>

  

  <!-- Nav Item - User Information -->
  <li class="nav-item dropdown no-arrow">
    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
      aria-haspopup="true" aria-expanded="false">
      <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ auth()->user()->name }}</span>
    </a>
    <!-- Dropdown - User Information -->
    <div class="dropdown-menu dropdown-menu-left shadow animated--grow-in" aria-labelledby="userDropdown">
      <a class="dropdown-item" href="#">
        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
        Settings
      </a>
      <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
        Logout
      </a>
    </div>
  </li>

</ul>

</nav>
<!-- End of Topbar -->

resources/views/theme/sidebar.blade.php
<!-- Sidebar -->

<ul class="pr-0 navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
        <div class="sidebar-brand-icon">
                <img style="width:70%" src="{!! asset('logo.png') !!}">
        </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item {{ request()->is('admin') ? 'active' : '' }}">
    <a class="nav-link text-right" href="{{ route('admin.index') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>لوحة التحكم</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <li class="nav-item {{ request()->is('admin/books*') ? 'active' : '' }}">
        <a class="nav-link text-right" href="{{ route('books.index') }}">
            <i class="fas fa-book-open"></i>
            <span>الكتب</span>
        </a>
    </li>

    <li class="nav-item {{ request()->is('admin/categories*') ? 'active' : '' }}">
        <a class="nav-link text-right" href="{{ route('categories.index') }}">
            <i class="fas fa-folder"></i>
            <span>التصنيفات</span>
        </a>
    </li>

    <li class="nav-item {{ request()->is('admin/authors*') ? 'active' : '' }}">
        <a class="nav-link text-right" href="{{ route('authors.index') }}">
            <i class="fas fa-pen-fancy"></i>
            <span>المؤلفون</span>
        </a>
    </li>

    <li class="nav-item {{ request()->is('admin/publishers*') ? 'active' : '' }}">
        <a class="nav-link text-right" href="{{ route('publishers.index') }}">
            <i class="fas fa-table"></i>
            <span>الناشرون</span>
        </a>
    </li>
    @can('update-users')
        <li class="nav-item {{ request()->is('admin/users*') ? 'active' : '' }}">
            <a class="nav-link text-right" href="{{ route('users.index') }}">
                <i class="fas fa-users"></i>
                <span>المستخدمون</span>
            </a>
        </li>
    @endcan

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->